### ISSUE TITLE
help !!!

### ISSUE THREAD

**Issue by czy2134** [EadCat/APAP-Image-Stitching#3]
Hi, it's a nice code.
I am a beginner who is learning image-stitching.
I don't know how to use the code to calculate the RMSE of image1 and image2.
Could you please write it?
Thanks you very much.
![image](https://user-images.githubusercontent.com/46508512/140476750-be5f405b-a7df-4af9-8b99-188b43b82a31.png)

**Comment by EadCat** [comment]
Hello.
Do you mean the benchmarking in section 4.2 in the paper?

**Comment by czy2134** [comment]
yes
![image](https://user-images.githubusercontent.com/46508512/140598707-c653626a-537f-49ec-91e2-c1d939025756.png)
I dont

**Comment by EadCat** [comment]
After the RANSAC, you can use the SIFT matching point between the source and destination image. 
Of course, you can split these matching points randomly by modifying the source code. 
<img width="1500" alt="20211125175435" src="https://user-images.githubusercontent.com/59416168/143410167-88589e66-6dd0-4c3f-9e48-f1d797d59df2.png">

But I'm not sure what "train" and "test" mean in the paper.

I guess after warping the matching points of the source image using APAP, they measured the distances of the matching points (of test set) between src & dst images within the stitched output.

Note that I used OpenCV for the SIFT instead of VLFeat, and this program stitches inputs recursively (to alleviate perspective distortions).

**Comment by czy2134** [comment]
Thanks for your reply.
I don't know how to get warping the matching points of the source image using APAP.
![image](https://user-images.githubusercontent.com/46508512/143419583-44fd309e-7880-4790-b9fa-e3b119ce63f1.png)
Can I re-extract feature points from the warped image pair by SIFT?

**Comment by EadCat** [comment]
I didn't consider quantitative evaluation, so it is impossible to extract the warped points with this source code.
You need to modify the code to track the warped matching points. The class responsible for APAP warping may be modified to store feature point coordinates.
